### ISSUE TITLE
Verification meta issue

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-zcash#3]
Meta-issue to synchronize verification rules development. High-level list of what needs to be done + current status:
- [x] Block pre-verification (`verify_block.rs`): completed;
- [x] Header pre-verification (`verify_header.rs`): completed (with local equihash impl);
- [ ] Transaction pre-verification (`verify_transaction.rs`): completed, except for [zk-SNARKs verification](https://github.com/zcash/zcash/blob/master/src/main.cpp#L1076);
- [x] Block verification (`accept_block.rs`): in-progress, needs check, detailed list:
- - [x] finalized transactions;
- - [x] BIP34;
- - [x] founders reward.
- [x] Header verification (`accept_header.rs`): in-progress, needs check, detailed list:
- - [x] work required;
- - [x] timestamp;
- - [x] version.
- [ ] Transaction verification (`accept_transaction.rs`): in-progress, needs check, detailed list:
- - [x] version, version group if && flags checks;
- - [x] drop expired transactions;
- - [x] size limits;
- - [x] SignatureHash (probably take from `SegWit`?);
- - [ ] join split - related checks;
- - [ ] sapling - related checks;
- - [x] sigops checks;
- - [x] coinbase-related checks (maturity, protected, ...);
- - [x] script checks;
- - [x] money range checks;
- [x] check && disable/enable verification-related BIPs / ZIPs
